okcomputer/fraud/urls.py
from django.urls import path
from . import views

app_name = 'fraud'

urlpatterns = [
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('landing/',views.landing, name = 'landing'),
    path('check/',views.Create_Transaction.as_view(),name = 'check'),
    path('result/',views.result,name = 'result'),
    path('transactionlist/',views.TransactionListView.as_view(),name='transaction_list'),
    ]

okcomputer/fraud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete= models.CASCADE)  #this class is an extension to the inbuilt User Model and this line says that the user object is Primary Key
    #additional objects besides the User model
    profile_pic = models.ImageField(blank= True , upload_to ='profile_pics')

    def __str__(self):
        return self.user.username

PAYMENT_METHODS = [('cashout', 'CASH OUT'), ('payment','PAYMENT'), ('cashin','CASH IN'), ('transfer','TRANSFER'), ('debit', 'DEBIT')]

class Transaction(models.Model):

    step = models.IntegerField(default=0)
    amount = models.FloatField(default=0)
    nameOrig = models.CharField(max_length=200)
    old_balance_org = models.FloatField(default=0)
    new_balance_org = models.FloatField(default=0)
    nameDest = models.CharField(max_length=200)
    old_balance_dest = models.FloatField(default=0)
    new_balance_dest = models.FloatField(default=0)
    transaction_type = models.CharField(max_length = 20,choices=PAYMENT_METHODS,default='cashout')
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    testing = models.CharField(max_length=200,default='null')
    

    def __str__(self):
        return str(self.amount)
    def get_absolute_url(self):
        return reverse('fraud:result')
    

okcomputer/fraud/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    password.widget.attrs['class']='form-control'
    class Meta:
        model = User
        fields = {'username' , 'email' , 'password'}
        widgets = {
            'username' : forms.TextInput(attrs = {'placeholder': 'Username', 'class':'form-control'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'E-Mail', 'class':'form-control'}),
            'password' : forms.PasswordInput(attrs = {'placeholder': 'Password', 'class':'form-control'}),
        }


class UserExtra(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = {'profile_pic'}




        

okcomputer/fraud/views.py
from django.shortcuts import render
from . import forms,models
from .forms import UserForm,UserExtra
from .models import Transaction
from django.views.generic.edit import CreateView
from django.views.generic import ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .pred import getPredictions




#Imports needed for Login

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request, 'fraud/index.html')

def register(request):

    registered = False                  # first we assume that the user has not registered

    if request.method == 'POST':
        user_form = UserForm(request.POST)  #   # these two variables are instances of the model forms while request is post
        profile_form = UserExtra(request.POST)

        if user_form.is_valid() and profile_form.is_valid():        #checks wheather the two forms are valid

            user = user_form.save()             #saves the data from the form
            user.set_password(user.password)    #sets the password , also hashing is undergone
            user.save()                         #saves data and pswd

            profile = profile_form.save(commit=False)  #we need to check wheather profile pic is present, so data is not added to the db
            profile.user = user  #defines the one to one relation of user that is shown in models

            if 'profile_pic' in request.FILES: #
                profile.profile_pic = request.FILES['profile_pic']  #if we included pro pic we assign it to the db and request.FILES is actually a dict of all the files added to form

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors) #shows error if form is invalid

    else:
         user_form = UserForm()
         profile_form = UserExtra()

    return render(request, 'fraud/registration.html',context={'user_form':user_form , 'profile_form' :profile_form, 'registered':registered})

def user_login(request):

    if(request.method == 'POST'):
        username = request.POST.get('username')  #recieves username and password from the form
        password = request.POST.get('password')

        user = authenticate(username = username, password= password)  #user variable is a boolean which holds the value returned by builtin authenticate fn

        if user:
            if user.is_active:       #django checks if user is authenticated
                login(request,user)  #inbuilt function which logs in automatically
                return render(request,'fraud/transaction_list.html')

            else:
                return HttpResponse('The Account is Currently Inactive')

        else:       #if user hasnt registered yet

            print("Username - {} and pswd - {}".format(username,password))      #outputs to console about details of invalid login attempts
            return HttpResponse('Invalid login details, Please Check if you have Registered')

    else:
        return render(request,'fraud/login.html')  #

@login_required                                         #decorator will only run this function if user has logged in
def user_logout(request):                   #logs out user
    logout(request)                                     #inbuilt function
    return HttpResponseRedirect(reverse('fraud:login'))

@login_required
def landing(request):

    return render(request, 'fraud/landing.html')

class Create_Transaction(LoginRequiredMixin,CreateView):
    fields = ['step', 'amount', 'nameOrig','old_balance_org', 'new_balance_org', 'nameDest', 
                  'old_balance_dest', 'new_balance_dest', 'transaction_type']
    model = Transaction

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

class TransactionListView(ListView):
    model = Transaction
    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)

class TransactionDetailView(DetailView):
    model = Transaction



def result(request):
    t = Transaction.objects.last()
    result = getPredictions(Transaction.objects.last())
    t.testing = result
    print(t.testing)
    t.save()
    return render(request, 'fraud/result.html',{'result':result})

okcomputer/templates/fraud/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>

        </title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Montserrat&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
              <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <nav id="navbar" class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <a class="navbar head" href="">okcomputer</a>
                <ul class="navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                    <li><a class="navbar-brand" href="{% url 'fraud:register' %}">Register</a></li>
                    <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-brand" href="{% url 'fraud:logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-brand" href="{% url 'fraud:login' %}">Login</a></li>
                {% endif %}
                </ul>
            </div>
        </nav>

        <script type="text/javascript">
        var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
var currentScrollPos = window.pageYOffset;
if (prevScrollpos > currentScrollPos) {
  document.getElementById("navbar").style.top = "0";
} else {
  document.getElementById("navbar").style.top = "-120px";
}
prevScrollpos = currentScrollPos;
}
        </script>
        {% block body_block %}
        {% endblock %}

    </body>
</html>

okcomputer/templates/fraud/check.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}
 
{% block body_block %}
<div  class = 'jumbo-tron'>

<h4 class="check">Enter The Transaction Details :</h4>
<form class="form-signin login-form" action="{% url 'fraud:result' %}" enctype="multipart/form-data" method="POST">
    <div>
        <div>
            {% csrf_token %}
            {{ form.as_p }}
        </div>
    </div>

    <input class="btn btn-lg btn-light btn-block form-control" type='submit' value='Check'>
</form>
</div>
{% endblock %}

okcomputer/templates/fraud/index.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}

    <h2>OKComputer</h2>
<a href="#about">
<i class="fa fa-chevron-down icon-down"></i></a>

    <div class="container">
      <div class="jumbo-tron">
          <div id="about" class="index-content">
            <h3>About us</h3>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


      {% if user.is_authenticated %}
      <button class="index-button btn btn-lg btn-light form-control"><a href="{% url 'fraud:check' %}">add a transaction</a></button>
      {% else %}
      <button class="index-button btn btn-lg btn-light form-control"><a href="{% url 'fraud:login' %}">Login</a></button>
      <button class="index-button btn btn-lg btn-light form-control"><a href="{% url 'fraud:register' %}">Register</a></button>
      {% endif %}
  </div>
  </div>
    </div>

    <footer class="footer">
      © okcomputer <br>
      2020
    </footer>
{% endblock %}

okcomputer/templates/fraud/landing.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}

<h4>Welcome to OK Computer (details about this site)</h4>


<button class="btn btn-lg btn-light"><a href="{% url 'fraud:check' %}">Check</a></button>

{% endblock %}
 

okcomputer/templates/fraud/login.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}
<div class="bg">


    <form class="form-signin login-form" action="{% url 'fraud:login' %}" method="POST">
        {% csrf_token %}
        <input class="form-control" type="text" name = 'username' placeholder="Enter Username"> <br>
        <input class="form-control" type="password" name = 'password' placeholder="Password">
        <input class="btn btn-lg btn-light btn-block form-control" type="submit" value="Login">
    </form>
</div>
{% endblock %}

okcomputer/templates/fraud/registration.html
<!DOCTYPE html>
{% extends 'fraud/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbo-tron bg-reg">
    {% if registered %}
        <h1 style="text-align: center" >Thank You for Registering</h1>
    {% else %}
        <!-- <h1 style="margin-left:39%">Register Here !</h1>
        <h4 style="margin-left:42%">Fill Out The Form</h4> -->
        <form class="form-signin login-form" enctype="multipart/form-data" method = 'post'>
            {% csrf_token %}
            {{ user_form.username }} <br>
            {{ user_form.password }} <br>
            {{ user_form.email }}<br>
          <div style="color:white">
            {{ profile_form.as_p }}
          </div>
            <input  class="btn btn-lg btn-light  btn-block form-control" type="submit" name="" value="Register">
        </form>
    {% endif %}

</div>
{% endblock %}

okcomputer/templates/fraud/result.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}
<h4>Displays The Result</h4>
<div class="alert alert-primary" role="alert">
  {{result}}
</div>

  <a href="{% url 'fraud:transaction_list' %}" class="btn btn-light">See All Transactions</a>
{% endblock %}

okcomputer/templates/fraud/transaction_detail.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}

  <div class="container p-3">
    <div class="card">
    <div class="card-header">
      {{user.username}}
    </div>
    <div class="card-body">
      <h5 class="card-title">{{transaction.amount}} rs</h5>
      <button type="button" class="btn btn-primary">
        {{transaction.testing}} <span class="badge bg-secondary"></span>
        <span class="visually-hidden"></span>
      </button>
      <a href="{% url 'fraud:transaction_list' %}" class="btn btn-primary">see details</a>
    </div>
  </div>
  </div>
{% endblock %}

okcomputer/templates/fraud/transaction_form.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}

<h4>Enter The Transaction Details :</h4>
<div class="tra-form">
<form  class="form-signin login-form" method="POST">


    <div style="color: white">
        <div>
            {% csrf_token %}
           {{ form.as_p }}<br>
        </div>
    </div>

    <input class="btn btn-lg btn-light" style="margin-left:2rem" type='submit' value='Check'>
</form></div>
{% endblock %}

okcomputer/templates/fraud/transaction_list.html
<!DOCTYPE html>
{% extends 'fraud/base.html'%}

{% block body_block %}





    <a href="{% url 'fraud:check' %}" class="btn btn-primary">add a transaction</a>
    {%for transaction in transaction_list%}
    <div class="container p-3">
      <div class="card">
      <div class="card-header">
        {{user.username}}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{transaction.amount}} rs</h5>
        <button type="button" class="btn btn-primary">
          {{transaction.testing}} <span class="badge bg-secondary"></span>
          <span class="visually-hidden"></span>
        </button>
        <a href="{% url 'fraud:transaction_list' %}" class="btn btn-primary">See Details</a>
      </div>
    </div>
    </div>
    </div>
    </main>
      {%endfor%}
</div>


{% endblock %}